import os
import hmac
import hashlib
import httpx
import logging
from typing import Dict, Any, Optional

logger = logging.getLogger("razorpay_service")

class RazorpayService:
    def __init__(self):
        self.key_id = os.getenv("RAZORPAY_KEY_ID", "")
        self.key_secret = os.getenv("RAZORPAY_KEY_SECRET", "")

    def is_configured(self) -> bool:
        return bool(self.key_id and self.key_secret and not self.key_id.startswith("rzp_test_YOUR"))

    async def create_razorpay_order(self, amount_in_rupees: float, receipt_id: str) -> Dict[str, Any]:
        """
        Creates an official Razorpay Order for UPI / Card checkout.
        Amount is converted to paise (INR * 100).
        """
        amount_in_paise = int(round(amount_in_rupees * 100))

        if not self.is_configured():
            logger.info("Razorpay credentials not configured. Generating test mock order.")
            return {
                "success": True,
                "mock": True,
                "razorpay_order_id": f"order_mock_{receipt_id}",
                "amount": amount_in_paise,
                "currency": "INR",
                "key_id": self.key_id or "rzp_test_mock"
            }

        url = "https://api.razorpay.com/v1/orders"
        auth = (self.key_id, self.key_secret)
        payload = {
            "amount": amount_in_paise,
            "currency": "INR",
            "receipt": receipt_id,
            "payment_capture": 1
        }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.post(url, auth=auth, json=payload)
                resp_data = response.json()

                if response.status_code in (200, 201):
                    return {
                        "success": True,
                        "mock": False,
                        "razorpay_order_id": resp_data.get("id"),
                        "amount": resp_data.get("amount"),
                        "currency": resp_data.get("currency"),
                        "key_id": self.key_id
                    }
                else:
                    logger.error(f"Razorpay API Error ({response.status_code}): {resp_data}")
                    return {
                        "success": False,
                        "error": resp_data.get("error", {}).get("description", "Failed to create Razorpay order"),
                        "status_code": response.status_code
                    }
        except Exception as e:
            logger.exception("Failed to connect to Razorpay API")
            return {
                "success": False,
                "error": str(e)
            }

    def verify_payment_signature(self, razorpay_order_id: str, razorpay_payment_id: str, razorpay_signature: str) -> bool:
        """
        Validates HMAC SHA-256 signature generated by Razorpay Checkout.
        """
        if not self.key_secret or razorpay_order_id.startswith("order_mock_"):
            # Accept mock signatures in test mode
            return True

        msg = f"{razorpay_order_id}|{razorpay_payment_id}"
        generated_signature = hmac.new(
            self.key_secret.encode('utf-8'),
            msg.encode('utf-8'),
            hashlib.sha256
        ).hexdigest()

        return hmac.compare_digest(generated_signature, razorpay_signature)

    async def create_payment_link(self, amount_in_rupees: float, receipt_id: str, name: str, email: str, phone: str, callback_url: str) -> Dict[str, Any]:
        """
        Creates an official Razorpay Payment Link for browser redirect checkout.
        """
        amount_in_paise = int(round(amount_in_rupees * 100))

        if not self.is_configured():
            logger.info("Razorpay credentials not configured. Generating mock payment link redirect.")
            mock_url = f"{callback_url}?razorpay_payment_id=pay_mock_123&razorpay_payment_link_id=plink_mock_123&razorpay_payment_link_reference_id={receipt_id}&razorpay_payment_link_status=paid&razorpay_signature=mock_sig"
            return {
                "success": True,
                "mock": True,
                "short_url": mock_url
            }

        url = "https://api.razorpay.com/v1/payment_links"
        auth = (self.key_id, self.key_secret)

        clean_phone = "".join(filter(str.isdigit, phone))
        if len(clean_phone) == 10:
            clean_phone = "91" + clean_phone
        if not clean_phone.startswith("+"):
            clean_phone = "+" + clean_phone

        payload = {
            "amount": amount_in_paise,
            "currency": "INR",
            "accept_partial": False,
            "reference_id": receipt_id,
            "description": "Payment for MakeWithMojo creations",
            "customer": {
                "name": name,
                "email": email,
                "contact": clean_phone
            },
            "notify": {
                "sms": False,
                "email": False
            },
            "reminder_enable": False,
            "callback_url": callback_url,
            "callback_method": "get"
        }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.post(url, auth=auth, json=payload)
                resp_data = response.json()

                if response.status_code in (200, 201):
                    return {
                        "success": True,
                        "mock": False,
                        "payment_link_id": resp_data.get("id"),
                        "short_url": resp_data.get("short_url"),
                        "status": resp_data.get("status")
                    }
                else:
                    logger.error(f"Razorpay Payment Link API Error ({response.status_code}): {resp_data}")
                    return {
                        "success": False,
                        "error": resp_data.get("error", {}).get("description", "Failed to create payment link"),
                        "status_code": response.status_code
                    }
        except Exception as e:
            logger.exception("Failed to connect to Razorpay Payment Link API")
            return {
                "success": False,
                "error": str(e)
            }

    def verify_payment_link_signature(self, payment_link_id: str, payment_link_reference_id: str, payment_link_status: str, payment_id: str, razorpay_signature: str) -> bool:
        """
        Validates HMAC SHA-256 signature generated by Razorpay Payment Links.
        """
        if not self.key_secret or payment_link_id.startswith("plink_mock_"):
            return True

        msg = f"{payment_link_id}|{payment_link_reference_id}|{payment_link_status}|{payment_id}"
        generated_signature = hmac.new(
            self.key_secret.encode('utf-8'),
            msg.encode('utf-8'),
            hashlib.sha256
        ).hexdigest()

        return hmac.compare_digest(generated_signature, razorpay_signature)

razorpay_service = RazorpayService()

